### ISSUE TITLE
Promise executor

### ISSUE THREAD

**Issue by LeeHowes** [executors/futures#10]
I've added the following text in the draft document:

template<class T>
class standard_promise {
public:
    using promise_default_executor = implementation-defined;

    standard_future<T, promise_default_executor> get_future();
    standard_semi_future<T> get_semi_future();
};

> The default executor type for promises allows for efficient promise->future
> code. This executor is intended for use only locally. It may be optimised
> using thread-local storage and should not be constructible. It is not copyable
> and its lifetime is not guaranteed to outlive a single continuation chain
> starting with a promise.
> 

The reason for this is that there is value in being able to grab a future from a promise, and chain off that future, with minimal cost.  This is the common use case for inline executors.

At the same time, one of the goals of the SemiFuture work I have been doing is to try to avoid people using inline executors. We don't want to encourage people to get a SemiFuture back from an API and promptly put an inline executor on it, and we certainly want to be able to catch it through code review/linting tools.

In folly we achieve this by adding toUnsafeFuture to SemiFuture, which helps in code conversion to convert from the leaves in. We have strongly considered having an UnsafeFuture type, which is continuable but without an executor, to use in these local in-project cases where completion can call through directly. It amounts to much the same use case as a zero-overhead task in Gor's coroutine thinking.

My alternative proposal is the above - that we allow an explicit operation on the promise type to get us a future with weaker guarantees, but we do that while keeping the precise executor type under implementation control so people cannot rely on its interface.

**Comment by LeeHowes** [comment]
Concept, no. Type, maybe.

**Comment by brycelelbach** [comment]
@LeeHowes is this still what we want, given the direction we have taken in executors with promises? Can you link the relevant issues from the executors repo?

**Comment by brycelelbach** [comment]
I'm closing this as we have nothing actionable here. We've decided on a direction here; we're adding a promise property to executors, and we have draft wording for that.
