### ISSUE TITLE
definition of std::this_thread::future_get refers to std::decay_t<Future>::value_type

### ISSUE THREAD

**Issue by RedBeard0531** [executors/futures#103]
But the concept doesn't require `::value_type`. Should `future_get` use `future_value_t` or should we add `SF<T>::value_type` to the concept. I personally think both would be best for consistency with other types that provide `::value_type`, but it seemed like the consensus in #31 went the other way. I'd be happy to make the wording change if you tell me which way you want it to go.

**Comment by LeeHowes** [comment]
Please change to use future_value_t.

I would like value_type too but as you point out we agreed to focus on the trait style.

**Comment by dhollman** [comment]
@LeeHowes Should the same apply to the `Promise` concept?

**Comment by LeeHowes** [comment]
I suppose so... let's be consistent. This is LEWG territory really I think.

**Comment by dhollman** [comment]
Fixing this now, btw.

**Comment by dhollman** [comment]
should be fixed; this can be closed with #106 is accepted.

**Comment by LeeHowes** [comment]
Closing.
