### ISSUE TITLE
Markup is a bit busted right now

### ISSUE THREAD

**Issue by RedBeard0531** [executors/futures#104]
A few examples I noticed while trying to read the rendered version:

- [ ] The first line of the intro looks like the *'s are not causing italics, presumably due to the embedded link
- [ ] double * in FAQ
- [ ] # marks in 2.1. Future/Promise Model
- [ ] [this sentence](https://github.com/executors/futures/blob/bb35a03675a0eedccd549067ef104e6d23264418/futures.bs#L171) is unfinished and blends with the next line
- [ ] "[called by the calling thread](https://github.com/executors/futures/blob/bb35a03675a0eedccd549067ef104e6d23264418/futures.bs#L183)" cancelling thread?
- [ ] [this line](https://github.com/executors/futures/blob/bb35a03675a0eedccd549067ef104e6d23264418/futures.bs#L200) isn't getting an extra layer of nesting. Also, not markup related, but that sentence can't possibly be right. Why would fulfilling the promise make a unique future invalid?

I'll edit this to add more as I read.

**Comment by LeeHowes** [comment]
1 is fixed in https://github.com/executors/futures/pull/99 which someone can approve and merge if they like :)

**Comment by griwes** [comment]
I think the comment about the sentence not being right is right: I think it misses "the *promise* becomes invalid" or something like that. I'll try to spec that correctly.

**Comment by griwes** [comment]
What is the unfinished sentence trying to say? I'm tempted to just strike that note.

**Comment by griwes** [comment]
Oh nvm. Found it.

**Comment by griwes** [comment]
Actually what I suggested for the sentence about fullfilment would be redundant, since that's specified by the `Promise` concept already.

**Comment by griwes** [comment]
I can solve these, but it kinda makes little sense for me to submit a PR until the other two are merged.
