### ISSUE TITLE
Requirements of `.via` return type

### ISSUE THREAD

**Issue by LeeHowes** [executors/futures#12]
See https://github.com/executors/executors/issues/378

**Comment by LeeHowes** [comment]
I've currently implemented via using then:
```
  return standard_future<T, NextExecutor>{
    std::move(this->core_), std::forward<NextExecutor>(exec)}.then(
      HelperF{});
```

and a public callback:
```
  // Should be called only by executor implementations
  // Callback should perform only trivial work to let the executor know
  // how to proceed.
  void set_callback(
      std::experimental::execution::future_completion_token<T>&& token){
    core_->set_task(std::move(token));
  }
```

.then defers to Executor::then_execute, which calls back to set_callback to set a callback that carries a completion token, which is an operation that can be performed on the executor to trigger dependent work on the future:
```
  template<class Function, class Future>
  auto then_execute(Function func, Future fut) const noexcept
      -> std::experimental::standard_future<
          std::result_of_t<Function(std::decay_t<typename Future::value_type>&&)>, simple_then_executor> {

    // Chain by cosntructing new promise/future pair
    std::experimental::standard_promise<
      std::result_of_t<Function(std::decay_t<typename Future::value_type>&&)>>
        chainedPromise;
        
    // Get future directly because we know this future has that functionality
    // and to call .via would be recursive on this function
    auto returnFuture = chainedPromise.get_future(simple_then_executor{});

    // Then construct a completion token to perform the trivial enqueue action
    // which is all this particular executor type needs as it does not carry
    // chaining state.
    auto ct = execution::future_completion_token<std::decay_t<typename Future::value_type>>(
      [promise = std::move(chainedPromise),
       func = std::move(func)](typename Future::value_type&& val) mutable {
        // Completion token performs a trivial action on the source future's
        // executor.
        // Usually an operation that amounts to triggering execution of the
        // actual completion task on the next executor.
        // As for this executor completion is via a promise/future pair
        // we simulate this by creating a trivial inline_executor to run it on
        inline_executor{}.execute(
          [   promise = std::move(promise),
              val = std::move(val),
              func = std::move(func)]() mutable {
            promise.set_value(func(std::move(val)));
          });
      }
    );
    // End the future chain by setting the action it shold perform
    std::move(fut).set_callback(std::move(ct));
    return returnFuture;
  }
```

This has the property of exposing an additional, confusing, set_callback operation on the future, and having the future call the executor which calls back to the future.

The goal of proposing that all executors expose some way to go get such a token - a promise type that exposes set_value as an operation, and which the future can package up in its own callback and satisfy with .via. In effect, exactly what I did above, except the public API moves to the executor providing a way to get the token, and the future can call set_callback internally, if that is how it works.

Promise in this case is a concept, not an implementation. It is just a type with a pair of functions. What the executor does with it is entirely flexible, as long as it can be obtained by the future, and its functions can be called from a weak agent.

**Comment by LeeHowes** [comment]
Because I have defined the future returned by the query to not be an explicit future type, this should be implementation-defined.

**Comment by brycelelbach** [comment]
Triage this after the Rapperswil mailing deadline.

**Comment by brycelelbach** [comment]
@LeeHowes confirm this has been done?

**Comment by LeeHowes** [comment]
The concrete types don't do this. Open to discussion either way. The concepts do.
