### ISSUE TITLE
std::future functionality and design constraints: construction, destruction, and assignment

### ISSUE THREAD

**Issue by dhollman** [executors/futures#16]
(Aspect 1 from #15)

To summarize the slides from the first meeting, `std::future` currently meets the following "concepts" in common use:

- `DefaultConstructible`
- `MoveConstructible`
- `MoveAssignable`
- `Destructible`
- `Swappable` (via `MoveAssignable`)

I don't think these present any issues for just about any `Future` concept we've imagined so far.

Conditionally Blocking Destructor
=================================

I think the main design decision here is the blocking behavior of the destructor and whether that gets exposed at the concept level, broadly speaking.  The standard currently states in [futures.states]/5.3 about operations that "release shared state" (that is, the destructor and the move assignment operator)

> these actions will not block for the shared state to become ready, except that it may block if all of the following are true: the shared state was created by a call to `std::async`, the shared state is not yet ready, and this was the last reference to the shared state.

Because `std::async` is called out specifically, does this mean that a `std::future` created by a call to `ex.twoway_execute()` doesn't necessarily block on destruction?

**Comment by brycelelbach** [comment]
We decided at Jacksonville that the future concept will not have a conditionally blocking destructor, but that the conditionally blocking destructor in `std::future` will have to stay for legacy reasons.

When we talk about `standard_future` in the context of this paper, we usually mean "new `std::future`", which would not have conditional blocking in the destructor.

**Comment by griwes** [comment]
More importantly, do we actually need it in a way that can't be satisfied with an `optional<future<T>>`?

**Comment by griwes** [comment]
Re: destructors, see also my comment under #28.

**Comment by brycelelbach** [comment]
I'm gonna close this one. I think it's fine for `std::future`s dtor to keep doing its thing, because we can't change it. We won't put a requirement in the future concept to **not** block in the destructor.
