### ISSUE TITLE
std::future functionality and design constraints: wait() and get()

### ISSUE THREAD

**Issue by dhollman** [executors/futures#17]
(Aspect 2 from #15)

My old slides from the first meeting conceptified the presence of `get()` and `wait()` via `GettableFuture` and `WaitableFuture`. Granularity of concept definition aside, it's helpful to think about the presence or absence of `get()` and `wait()` in the context of executor needs, particularly with respect to their current behavior in `std::future`.

Current Definition
==================

Currently, [futures.unique_future]/20 provides a pretty minimal description of `wait()`.  The entire text pertaining to `wait()` is:

> `void wait() const;`<br>
>   *Effects:* Blocks until the shared state is ready.

A more precise definition of the terms "shared state" and "ready" is given in [futures.state].  Of particular relevance is paragraph 3:

> An asynchronous return object is an object that reads results from a shared state. A waiting function of an asynchronous return object is one that potentially blocks to wait for the shared state to be made read.

The standard defines `get()` in terms of `wait()` plus retrieval of the result (value or exception) and release of shared state (see [futures.unique_future]/15)

Executor Adaptations
====================

The main class of executor needs that the *waiting functions* address (beyond user-interface needs) are adaptations that involve "burning" an execution agent to implement the required adaptation. All of these adaptations that I can think are for adaptations to implement `then_execute` or `bulk_then_execute`.  Thus, it might be useful to explore certain requirements for executor needs in terms of a future supporting waiting functions *or* continuation passing (`then()`), which may be sufficient to implement many/most flavors of `then_execute`.

Forward Progress Guarantees
===========================

It's worth noting here (at least in passing) that an executor who's agents do not use *non-timed waiting functions* (or any other non-future concurrency constructs) on a future can have a relatively trivial forward progress guarantee, which may be useful both for executor implementability on some hardware and for relatively trivial forward progress delegation between disparate executor types.  (Of course, this comes at a substantial cost in terms of user interface, etc.)

**Comment by LeeHowes** [comment]
Earlier decision was to use free functions in thread. eg std::this_thread::wait(Future);

**Comment by LeeHowes** [comment]
David: Do we need constraints on where the wait function can be called from?

**Comment by dhollman** [comment]
I suspect the constraints would be the same on `wait` as on `get`, so the free function makes the most sense to me.  Can you think of any reasons why this should not be the case?

**Comment by LeeHowes** [comment]
No, I agree.

I was quoting you, not directing a question at you. I think both should be done the same way.

**Comment by brycelelbach** [comment]
Since we're going with the free functions, I'm gonna close this, I don't think there's anything actionable here.
