### ISSUE TITLE
What type of executor does `.via` require?

### ISSUE THREAD

**Issue by brycelelbach** [executors/futures#21]
What type of executor does `.via` require?

OR

What executor properties will `.via` require of an executor?

**Comment by brycelelbach** [comment]
@LeeHowes and @ccmysen please review.

**Comment by jaredhoberock** [comment]
> What executor properties are will .via require of an executor?
I agree that this is the best way to phrase the question.

**Comment by LeeHowes** [comment]
What properties seems fine.

I would say that there are two options for support, and they change the return type slightly:
1) The Executor is a promise-executor. This of course depends on our final agreement on how to deal with promises, but assuming my current proposal in the branch (with type changes) over in the executors doc that would mean we can call get_promise on it.  In this case the return type of .via would be:
`  decltype(e.get_promise<decltype(*this)::value_type>().get_future()); `
Or some approximation of that corrected for spec language. Actually, simply the future type of the executor might be appropriate here, it really depends on whether we use a single type or allow two separate ones. 
2) The executor is a one-way executor. Then the return type is either the same future type, modified with the executor attached (if the future can generate a promise/future pair) or a std::standard_continuable_future (post bikeshedding) if not. We can always support a std::standard_promise/std::standard_continuable_future.

**Comment by LeeHowes** [comment]
I've committed changes that attempt to provide a bound on this.

**Comment by brycelelbach** [comment]
> The executor is a one-way executor. Then the return type is either the same future type, modified with the executor attached (if the future can generate a promise/future pair) or a std::standard_continuable_future (post bikeshedding) if not. We can always support a std::standard_promise/std::standard_continuable_future.

I don't understand what the return type is here.

**Comment by brycelelbach** [comment]
Okay I've drafted some alternative wording for this based on what you committed.
