### ISSUE TITLE
Can multiple continuations be attached to a unique future?

### ISSUE THREAD

**Issue by brycelelbach** [executors/futures#25]
E.g.

```
std::experimental::future<int> f;
f.then(g);
f.then(h);
```

The sane answer IMHO is no, because if the answer is yes, you can't move out of the future's shared state, which is the whole point of unique futures.

**Comment by brycelelbach** [comment]
@LeeHowes and @jaredhoberock please review.

**Comment by griwes** [comment]
I second the opinion that the sane answer is NO.

What's the preferred failure mode? Throwing an exception?

**Comment by jaredhoberock** [comment]
One option could be to take a weaker/permissive stance on this and simply say that `unique_fut.then()` is not required to leave `unique_fut` in a valid state after it returns. There could be use cases for "multishot" `UniqueFuture`s that we haven't considered.

**Comment by LeeHowes** [comment]
I think Jared is right. We do not ban it for the concept, but the concept documentation should say that the future may be left in an invalid state. Or possibly a moved-from state, such that it is valid but unusable - via, get, then etc cannot be assumed to be callable on an instance of the concept. Destruction of course is safe. Whatever the current preferred language is for that condition.

**Comment by dhollman** [comment]
I agree with Jared. There's no reason to ban it in the concept, but you can effectively ban it in fully generic code by saying that the future may be left in an invalid state. If some executor wants to do otherwise (and wants to expose that property to generic code), they can make a user-defined executor property for it, and you can query the property from the future's `get_executor()` method.

**Comment by RedBeard0531** [comment]
If the answer to #30 (Should UniqueFuture only require then() to be callable on an rvalue) is yes, then that implicitly bans multiple continuations, making this question moot.

**Comment by brycelelbach** [comment]
I'm fine with making it UB (what @jaredhoberock and @LeeHowes have suggested). That is what I had in mind, although maybe that wasn't clear in my initial post. The wording already has the groundwork for this.

Action items:

* Add wording for `UniqueFuture` stating that calling .then multiple times is UB.

**Comment by dhollman** [comment]
> I'm fine with making it UB (what @jaredhoberock and @LeeHowes have suggested).

I'm not the expert on such things, but I don't think you use the UB wording for something not specified by a concept. It's still well-defined behavior for the concrete type (i.e., the compile-time behavior *is* defined), it's just that you can't rely on it working the same way for all `UniqueFuture` types in a generic context — I don't know what the exact word for this is, but I feel like it's not UB.

**Comment by LeeHowes** [comment]
The current text only requires ContinuableFuture to support r-value .then. In effect we get this by default. Closing.
