### ISSUE TITLE
Should `UniqueFuture::then` be rvalue-reference qualified?

### ISSUE THREAD

**Issue by brycelelbach** [executors/futures#30]
Should `.then` on unique futures be rvalue-reference qualified, since it consumes the value stored in the future? E.g.

```
template <typename Callable>
auto then(Callable f) &&;
```

@griwes and I explored this in P701r0 and P701r1 after Marshall Clow (I think) suggested it. Based on that experience, I think it's a bad idea. Consider:

```
unique_future<T> f = async(exec, F);
unique_future<U> g = f.then(G);
```

If `.then` was rvalue reference qualified, that code wouldn't work. You'd have to write:

```
unique_future<T> f = async(exec, F);
unique_future<U> g = std::move(f).then(G);
```

Ditto for `.get` on unique futures (which, note, is not currently part of the concept).

I'm pretty sure there are "consuming" APIs in the standard library today, although I can't think of any off the top of my head. It may be wise to do a search for such constructs so we can see what the precedence is. There are proposals in flight for similar things, like one-shot `std::function`s.

**Comment by brycelelbach** [comment]
@LeeHowes and @griwes please review.

**Comment by jaredhoberock** [comment]
`std::future::get()` is consuming, but it is not rvalue-reference qualified. Like Bryce, I'm having trouble thinking of examples, but my recollection is that the established convention is that consuming interfaces related to futures take lvalue references.

**Comment by dhollman** [comment]
> If .then was rvalue reference qualified, that code wouldn't work. You'd have to write:
>
```
unique_future<T> f = async(exec, F);
unique_future<U> g = std::move(f).then(G);
```
> Ditto for .get on unique futures 

But that's a feature, not a bug. It is a lot easier for linters (and humans, for that matter) to tell that a value is expired if expiration has two-sided naming semantics (i.e., `std::move` on the caller side and the `&&` qualifier on the callee side). Other languages (like rust, for instance) enforce this strictly (you need `&mut` on both sides). This idea makes so much sense that I think there is pretty substantial convention forming around this kind of thing in third-party libraries (`folly`, for instance, if I'm not mistaken).

That said, we have a crappy precedent in the standard for this kind of thing. Jared is right, `std::future::get()` is a prime example of something we probably would have done this way if implementation experience showing the value of rvalue ref qualifiers existed at the time. But it didn't, and so we didn't, and now we're stuck. I'm not sure where this leaves us, but I think probably the path of least resistance is to not bother with the reference qualifiers.

**Comment by brycelelbach** [comment]
@dhollman I'm not finding your argument for greppability sufficiently motivating here, given how unintuitive this will make using futures.

@LeeHowes thoughts?

**Comment by LeeHowes** [comment]
I agree that it is a feature not a bug. I have seen a lot of build failures of this sort moving folly::Future code to folly::SemiFuture, where we learned a bunch of lessons and decided to r-value qualify consuming functions (among other consistency improvements) - unfortunately that does not include .then, but it does include the .defer addition, and all the various destructive get methods. 

We have not attempted to r-value qualify folly::Future yet, simply because of the huge number of call sites already out there. SemiFuture was a new type so new use cases can make those changes and we've been happy with the result. None of the call sites were hard to fix, or was readability significantly harmed by the changes. A lot of futures are returned from functions anyway so doAsyncThing().then(...) doesn't need a change.

However, consistency with the standard is more important than consistency with folly of course. I would argue that we should aim for consistency with current standard practice, not old practice - what std::future does is irrelevant. What new APIs are doing having learned lessons matters.


The current proposal for get is to make it a free function in thread scope, so that would be perfectly consistent with other consuming functions by taking an r-value future.

**Comment by dhollman** [comment]
> @dhollman I'm not finding your argument for greppability sufficiently motivating here, given how unintuitive this will make using futures.

This isn't about greppability.  It's about a uniform syntax for expiration semantics. Consider:

```c++
// code I inherited (developer left for some other company)
auto obj = SomeUnfamiliarObject(42);
some_unfamiliar_function(obj);
another_unfamiliar_function(std::move(obj));
// end code I inherited

// <-- I have to start modifying code here
// Can I do anything with obj? Clearly not:
obj.familiar_method(); // pretty easy for human and/or linter to spot the error
```

Because of two-sided naming, I don't need to look at `some_unfamiliar_method()` (or even its signature) to know it's not the reason I can't call `familiar_method()`; it's clearly because `another_unfamiliar_method()` was called in the code. Now consider:

```c++
// code I inherited (developer left for some other company)
auto obj = SomeUnfamiliarObject(42);
obj.some_unfamiliar_method();
obj.another_unfamiliar_method();
// end code I inherited

// <-- I have to start modifying code here
// Can I do anything with obj?
// If I don't rvalue-ref qualify another_unfamiliar_method(),
// then I need to look at the implementation (or documentation,
// if it exists) of another_unfamiliar_method()
obj.familiar_method();
```

The reason this is so important is because expired value errors can't be caught at compile time (without a linter or something) under current C++ semantics, and even testing with full coverage might not uncover them:

```c++
// code I inherited (developer left for some other company)
auto obj = SomeUnfamiliarObject(42);
obj.some_unfamiliar_method();
if(some_very_rare_condition()) obj.another_unfamiliar_method();
// end code I inherited

// <-- I have to start modifying code here
if(another_unrelated_rare_condition()) obj.familiar_method();
```

You need *full path* coverage of your code to catch this bug, which very few codebases have.

I agree that using rvalue ref qualifiers is *unfamiliar* to developers who have been programming for decades, since before move semantics existed. But I would argue the inconsistency associated with *not* using them is more unintuitive.

**Comment by RedBeard0531** [comment]
I haven't spent enough time thinking about C++20 Concepts yet, so I spoke to ADAM about them earlier today. There is an interesting wrinkle that implies that regardless of whether you think the concrete Future types should have rval-qualifiers, we should be defining the interface in terms of rvalues for all methods we want to support chaining.

If we define the Future concept with something like `future_instance.then([](...){...})`, not only would it be illegal to add an rval-qualifier to then(), it would be *legal* to add a non-const lval-qualifier, which would ban chaining! Alternatively, if we define the concept like `std::move(future_instance).then([](...){...})` then concrete future types can choose to either put an rval-qualier or no qualifier, but they couldn't put a non-const lval-qualifer which is something I think we *do* want to ban.

**Comment by LeeHowes** [comment]
For what it's worth, a few days ago someone looked at the folly::Future code and asked me why ::then, ::get etc are not r-value qualified, arguing that they should be.

**Comment by LeeHowes** [comment]
Added r-value qualification. Currently only unique-future is in the document.

**Comment by brycelelbach** [comment]
I really do not want this to be rvalue-reference qualified, it makes it very difficult to work with. Let's discuss this tomorrow.

**Comment by brycelelbach** [comment]
I understand the desire behind using rvalue ref qualifiers, but the feature is **not designed to be used this way**. Rvalue ref qualifiers are useful for disambiguating an overload that should work differently from other overloads, **not** for restricting what people can do with an API.

Because of how rvalue references work and how deduction operates on rvalue references, making `.then` rvalue ref qualified would make unique futures basically unusable.

As I mentioned before, the following would not work:

```
unique_future<T> f = async(exec, F);
unique_future<u> g = f.then(G); // COMPILATION FAILURE

unique_future<T> f = async(exec, F);
unique_future<U> g = std::move(f).then(G);
```

What about `auto`? Nope:

```
auto f = async(exec, F);
unique_future<U> g = f.then(G); // COMPILATION FAILURE

auto f = async(exec, F);
unique_future<U> g = std::move(f).then(G);
```

Well, how about if `f` is `unique_future<T>&&` or `auto&&`? Nope, doesn't work either:

```
unique_future<T>&& f = async(exec, F);
unique_future<u> g = f.then(G); // COMPILATION FAILURE

unique_future<T> f = async(exec, F);
unique_future<U> g = std::move(f).then(G);
```

A function that takes a future by rvalue reference still has to move:

```
void foo(unique_future<int>&& f)
{
  f.then(bar); // COMPILATION FAILURE
}

void foo(unique_future<int>&& f)
{
  std::move(f).then(bar);
}
```

What does `.then` return in such a world? An rvalue reference?

```
template <typename T>
struct unique_future
{
  template <typename F>
  unique_future<declval<F>()(declval<T>())>&&
  then(F&& f) &&
  {
    return std::move(exec.then_execute(std::forward<F>(f), *this));
  }
};
```

This is **not** okay. We're returning a dangling reference - it's just as bad
as returning an lvalue reference to a temporary. After `.then` returns, the
temporary object will get destructed.

So we have to return by value instead:

```
template <typename T>
struct unique_future
{
  template <typename F>
  unique_future<declval<F>()(declval<T>())>&&
  then(F&& f) &&
  {
    return std::move(exec.then_execute(std::forward<F>(f), *this));
  }
};
```

But now it's very ugly to chain `.then` invocations:

```  
unique_future<int> f = async(exec, F); 
unique_future<int> g = j.then(F).then(G).then(I); // COMPILATION FAILURE

unique_future<int> f = async(exec, F); 
unique_future<int> i = std::move(std::move(std::move(f).then(G)).then(H)).then(I);
```

I really can't support an rvalue ref qualified API. I have explored it in the
past, and based on experience, it's really difficult to use.

**Comment by brycelelbach** [comment]
Rvalue ref qualifying `.via` has the same problems.

**Comment by griwes** [comment]
Your last argument is not valid, though - when you return something by-value, you can immediately call an `&&`-qualified member function on it: https://godbolt.org/g/kcNPBM

**Comment by brycelelbach** [comment]
@griwes is right, I am wrong. Sorry, it was late :p.

I think I am fine with rvalue ref qualifying it now. I don't love it, but I do see the benefits, and it eases the concept hierarchy.
