### ISSUE TITLE
Use global-scope traits instead of nested type aliases

### ISSUE THREAD

**Issue by brycelelbach** [executors/futures#31]
Requiring the definition of nested type aliases in a concept is annoying, because you can't provide a "default" definition, so type authors implementing your concept *must* define the nested type aliases. This pattern exists mostly for historical reasons:

* Pre C++11, these nested type aliases were often an unfortunate necessity (Boost/TR1 result_of and (unary|binary)_function, etc). Post C++11, this is frequently syntax sugar as these types can be discovered via `decltype`, etc.
* Pre C++11, using separate traits class customization points to define these types was unwieldy because we didn't have type aliases to save us from `typename` (e.g. `typename X<T>::type` instead of `X_t<T>`).

Iterators, containers, and allocators all suffer from this problem.

In modern C++, there's a better solution: define a traits class for each nested type aliases (not a single traits class for all the types, like `iterator_traits` or `numeric_traits`), provide a reasonable default, and allow users to customize it. For example:

```
template <typename MyConcept>
struct X { using type = /* default */; };

template <typename MyConcept>
using X_t = typename X<T>::type;
```

The executors proposal uses this pattern (`executor_future_t`, `executor_index_t`, etc). We should do the same.

**Comment by RedBeard0531** [comment]
I disagree. At the very least, I think Futures should follow the convention for wrapper types set by std::optional and (proposed) std::expected and offer `Future<T>::value_type = T`. 

If the problem is that concepts don't support default definitions of nested types, can we propose to fix that problem directly?

**Comment by jaredhoberock** [comment]
I think both approaches are viable. The default implementation of these traits can look for a nested type, and use it if it exists.

**Comment by brycelelbach** [comment]
Okay, what traits do we need?

Presumably we need `future_value_t`. Anything else?

Action items:
* Add `future_value_t` to paper.

**Comment by dhollman** [comment]
I'd vote for keeping traits pretty minimal in version 1 — it's super easy to run into resistance in the minutia of these sorts of things. I think later it's worth discussing traits for things like behavior and signature(s) supported by `.then()`, and maybe something describing unwrapping behavior. But I think `future_value_t` is basically all we need for version 1.
