### ISSUE TITLE
Should callbacks passed to Futures require copyability or can they be move-only?

### ISSUE THREAD

**Issue by RedBeard0531** [executors/futures#32]
Move-only callbacks arise naturally when capturing a unique_ptr into a lambda. Unfortunately they can't be put into a `std::function` because it requires copyability. Should we allow move-only callbacks to make consumers lives easier even if it prevents implementations that store the callback directly in a `std::function`?

I lean toward requiring support for move-only callbacks. I think you can add copyability to any movable callback by doing something like the following (untested) code, but I'd rather the burden to do so correctly be on the Future implementers than users.

```cpp
template <typename Func>
decltype(auto) ensureCopyable(Func&& func) {
    using FuncRaw = std::decay_t<Func>;
    if constexpr (std::is_copy_constructible_v<FuncRaw> && std::is_copy_assignable_v<FuncRaw>) {
        return std::forward<Func>(func);
    } else {
        return [func = std::make_shared<FuncRaw>(std::forward<Func>(func))] (auto... args) {
            return (*func)(std::forward<decltype(args)>(args)...);
        };
    }
}
```

**Comment by griwes** [comment]
Implementations should just use `std::unique_function` that's been proposed - the implementation is amazingly short, and we shouldn't require copyability just because `std::function` requires it.

**Comment by LeeHowes** [comment]
We should support move-only callbacks.

**Comment by brycelelbach** [comment]
Since we have `FutureContinuation`, we should just say it requires `MoveConstructible`.

**Comment by LeeHowes** [comment]
Made change to definition of FutureContinuation.

**Comment by RedBeard0531** [comment]
> Since we have FutureContinuation, we should just say it requires MoveConstructible.

Amusingly, the way FutureContinuation is defined it can't be put in a std::function anyway, making the only argument in favor of requiring copyability moot!
