### ISSUE TITLE
Should future::then(func) use func(val) or INVOKE(func, val) 

### ISSUE THREAD

**Issue by RedBeard0531** [executors/futures#33]
For the form where the callback is passed a future it doesn't make a ton of sense to use INVOKE. However, since we are leaning toward making then pass the value directly to the callback, it seems more useful. This would allow consumers to pass a pointer-to-member or pmf to then() without needing to write the artificial lambda.

**Comment by LeeHowes** [comment]
INVOKE means can pass pointer to member function without explicit lambda.

Bryce assumes we will use invoke.

If no objections we will do that.

**Comment by brycelelbach** [comment]
We should actually use `std::invoke` I believe.

**Comment by brycelelbach** [comment]
Hrm. Given that DECAY_COPY is used in the executors paper, I think we should just stick with INVOKE.

Note that the executors proposal doesn't actually use INVOKE anywhere.

**Comment by brycelelbach** [comment]
Changed my mind, back to `std::invoke`
