### ISSUE TITLE
Finalize logistical details for the 04/26/18 NVIDIA F2F meeting

### ISSUE THREAD

**Issue by brycelelbach** [executors/futures#35]
* [x] Send invites to
  * [x] Andrii
  * [x] @hkaiser
  * [x] @griwes 
  * [x] Thomas Rodgers
* [x] Confirm attendees list.
* [x] Add building address.
* [x] Add directions.
* [x] Physically confirm room.
* [x] Confirm food.

**Comment by griwes** [comment]
Friendly reminder that I'll need a way to call in.

**Comment by griwes** [comment]
(Was the title meant to say 04/**26**/18?)

**Comment by brycelelbach** [comment]
> (Was the title meant to say 04/26/18?)

Yes, fixed.
