### ISSUE TITLE
`Promise` concept

### ISSUE THREAD

**Issue by brycelelbach** [executors/futures#42]
There are two API options:

```
template <typename T>
struct promise {
  void set_value(T);
  void set_exception(exception_ptr p);
};
```

or

```
template <typename T>
struct promise {
  void operator()(T);
  void operator()(future_error_t, exception_ptr);
};
```

Also relevant is #37, which may encourage us to support:

```
template <typename T>
struct promise {
  void operator()(T);
  template <typename E>
  void operator()(future_error_t, E);
};
```

Or:

```
template <typename T, typename E>
struct promise {
  void operator()(T);
  void operator()(future_error_t, E);
};
```

**Comment by brycelelbach** [comment]
We discussed this at the NVIDIA F2F meeting, and decided we actually do want to do something for cancellation in version 1.

```
// Model 1b (current status quo): <-- We prefer this over 1a
struct promise
{
   void set_value(T value);
   void set_exception(E error);
};

std::pair<promise, future> make_promise(Executor exec);
// This is one executor property.

std::pair<promise, future> make_promise(Executor exec, CancellationCallback cc); // cc is void()
// This is another executor property.

auto [p, f] = make_promise(exec);
// ...
auto g = then_execute(other_exec, f, c);
p(v); // `f` is made ready with the value `v`.
      // After this, `c(v)` is executed on `other_exec` asynchronously; `g` is made ready with the result.
```

Poll: Proceed with model 1b (model 1 with cancellation)
SF F N A SA
4 2 1 0 0

Poll: Cancellation should be in version 1 (Rapperswil) of the paper
SF F N A SA
1 4 1 1 0

Action Items:
* [ ] (Lee) Combine executor property paper with this paper to bring in the promise concept and mechanism that we decided we want.
* [ ] (David) Afterwards, send a PR updating the wording to have the executor query mechanism return a factory instead of a pair.

**Comment by LeeHowes** [comment]
Initial merge of text in https://github.com/executors/futures/pull/51

**Comment by LeeHowes** [comment]
Closing. Text is in paper, we can tweak as general wording.
