### ISSUE TITLE
2018-04-26 Afternoon F2F Notes

### ISSUE THREAD

**Issue by dhollman** [executors/futures#44]
Concept overview (issue #27)
------------------

- `UniqueFuture` and `SharedFuture` concepts
  - Bryce: "Not all `SharedFuture`s satisfy `UniqueFuture`
  - Can you also have a non-const lvalue reference?

Straw Poll: Should `SharedFuture` be required to take a callable that takes a non-const lvalue reference as a 

- Sean: Concept model should be based on copyability of the `T` and not on 

Straw Poll:
Do we want three concepts, `SemiFuture`, `ContinuableFuture`, and `SharedFuture` (which linearly refine themselves)?
SF F N A SA: 0 6 3 0 0

Does version 1 of this paper need to have a fourth concept, `UniqueFuture`, which refines `ContinuableFuture`?
SF F N A SA: 0 0 2 7 0

**Comment by LeeHowes** [comment]
Closing this for tidiness. It is referenced from the related one so we can find the note.
