### ISSUE TITLE
Synchronisation of blocking wait operations

### ISSUE THREAD

**Issue by LeeHowes** [executors/futures#5]
Blocking wait operations need to be safe on a variety of different executing agents.

The proposal we made in P0904 was to leave that up to the executor. The executor already defines a future type as the return value of the two-way operations, when available. That future type should safely block on the execution agents in question, and provide appropriate underlying synchronization between setting the value and signally completion to the agent to wake it.

With this assumption, inter-device synchronization may be satisfied using the primitives in https://github.com/executors/futures/issues/3 with any additional synchronisation being deferred to how a particular two_way executor satisfies its future type.

Discuss.

**Comment by dhollman** [comment]
>  signally completion to the agent to wake it.

One problem I see with this is the "wake it" part. Coroutines aside, there's no general way to enqueue the continuation of an agent that may not be a thread. The executor may _transparently_ be reduced to polling as its only standards-conforming option (whereas, for instance, that executor could ensure that `wait()` is always cheap on its own futures by carefully regulating scheduling order). I'm always wary of things with vastly different costs that are spelled the same way. Maybe that's unavoidable with `get()` and `wait()`, but it would be nice if there were another way around this (like prohibiting certain adaptations of SemiFutures at compile time, maybe?)

**Comment by LeeHowes** [comment]
We don't have to worry so much about this. Use free functions.
