### ISSUE TITLE
Remove `get_*_future` functions from `standard_promise`

### ISSUE THREAD

**Issue by brycelelbach** [executors/futures#75]
I'm actually a little concerned about having these `get_*_future` in `standard_promise`.

Consider:

```
executor exec;

auto [p, f0] = exec.get_promise();

auto f1 = p.get_promise();
```

This is bad if `f`  is a unique future type.

[In the standard today, you can only retrieve a future once from a promise](). So, at best these functions should be rval-ref qualified.

However, given that people get promises by asking an executor for a future promise pair, when would you ever have a promise where you could retrieve the future from it?

I'd be okay with discussing this later down the road, but let's remove these for version 1.

P.S. This is assuming that the promise executor property still gives you a future-promise pair.

**Comment by LeeHowes** [comment]
Any executor that does return a standard_promise as part of its get_promise query should make it clear that the promise is pre-consumed. Most executors will presumably not do that because getting a standard future as the input future to then_execute is not especially useful without knowing how to manipulate the innards..

They shouldn't be rval-ref qualified because they are not destructive on the promise itself. Although you have a point that it wouldn't hurt to make it a free function that takes a standard_promise and turns it into a promise/future pair.

Maybe a free function that spins up a standard_promise + standard_semi_future is actually the cleaner API.

standard_promise is not the promise concept. It is for the same set of use cases as std::promise - where you need to decouple construction of the shared state from the function that runs it. For example, generating a promise + future to then use with a oneway executor, which is the way most of the world currently uses executors.

**Comment by dhollman** [comment]
> Any executor that does return a standard_promise as part of its get_promise query should make it clear that the promise is pre-consumed.

But we haven't defined any other use cases for `standard_promise`. It doesn't even define any constructors. Right now, every use we have for the `standard_promise` type would be pre-consumed.

I do actually think this is a V1 issue, given my comments on #46.  Here's how I would redesign it:

```c++
template <class T, class Error=std::exception_ptr>
class standard_promise {
public:
    using value_type = T;
    using error_type = Error;

    standard_promise(standard_promise&&) noexcept;
    template <typename Promise>
    // note: SFINAE to restrict to rvalue meeting promise concept, compatible T and Error,
    // and not standard_promise; deduction guides for value_type and error_type
    explicit standard_promise(Promise&& p);

    void set_value(const T& val) &&;
    void set_value(T&& val) &&;
    
    void set_exception(const Error& err) &&;
    void set_exception(Error&& err) &&;
};
```

I think this gets us back to the main purpose of `Promise`s in our paper — coordinating between differing executors when implementing `then()`.

Am I missing some other purpose that `standard_promise` was intended to accomplish?

**Comment by LeeHowes** [comment]
We can't do anything useful with a oneway executor without a standard promise type, can we? 

The use of standard promise is exactly the same as the use of std::promise, except that standard_promise has a future that is useful.

**Comment by LeeHowes** [comment]
You are right that it is missing a constructor, though, that needs to be fixed or replaced with the make_promise approach.

**Comment by dhollman** [comment]
> We can't do anything useful with a oneway executor without a standard promise type, can we?

Okay, so this is the piece I was missing.  Do we really need to do anything with a `OneWayExecutor`? By excluding `then_execute()` from an executor's interface, the executor author is basically saying "I can't efficiently queue up work with the mechanisms at my disposal." Isn't it then a bit odd for us to come along and say "well, we'll do it anyway"?

I have to think more about this, but I now think many of my concerns with the current state of the paper come down to changes made in the name of supporting the `OneWayExecutor` use case

**Comment by LeeHowes** [comment]
That is the world we live in now. It works fine for networking code. It just doesn't work for use cases like GPUs where letting the executor manage the queue is important.

If we have no future/promise pair in the standard that is non-blocking, I think it's debatable whether we should put oneway executor in. We'd just have to assume it worked with coroutines and not futures, which is possibly ok, but it'd be a shame to not have a workable traditional future type.

In principle, were I to be given the choice between dropping oneway, and dropping then, I'd drop then. That keeps us in a world we know well, and that we know works, and that gives us the executor support for coroutines.

**Comment by dhollman** [comment]
Okay, I think I understand now. In that case, I'd prefer to have the default constructor return an empty `standard_promise` and do the construction through two overloaded free functions:

```c++
template <typename T, typename Error=std::exception_ptr, typename Ex>
pair<standard_promise<T, Error>, standard_continuable_future<T, Ex>>
make_promise_contract(Ex)
  requires execution::is_oneway_executor_v<Ex> && !execution::can_query_v<Ex, promise_contract_t<T, Error>>;

template <typename T, typename Error=std::exception_ptr, typename Ex>
auto
make_promise_contract(Ex)
  requires execution::can_query_v<Ex, promise_contract_t<T, Error>>;
```

with the interface I proposed in the previous comment for `standard_promise`.

(Maybe also with `make_cancelable_promise_contract()` analogs?)

The advantage of this is that we still restrict the interface of `standard_promise` to what we need it for without introducing this fuzzy `promise_default_executor` thing.

**Comment by dhollman** [comment]
> That is the world we live in now.

So does that mean there's no way for an executor to statically say "don't enqueue work on me, it won't be efficient to do so?"

**Comment by LeeHowes** [comment]
Right, I think that's fine. Excepting that we should also have an executor-free one that makes a standard_promise + standard_semi_future, because there's no reason not to.

> So does that mean...

Well, surely an executor that can't accept work just won't be an executor? I think you must mean dependent/chained work? In which case I don't think oneway execution is less efficient than then_execution for the majority of use cases. Most code will just enqueue a callback lazily under the hood. Any then_executor I implement will be a oneway executor with a queue and a then wrapper on it.

**Comment by LeeHowes** [comment]
Oh, and you can define the executor-taking version of make_promise_contract directly in terms of the free query function, because it already does the rest of that can_query check.

**Comment by LeeHowes** [comment]
Can you approve #100, I'll merge it and we can either add the contract APIs + change the meaning of the constructor now or do that as 1.5

**Comment by LeeHowes** [comment]
It's a valid conclusion as well, btw, to decide that the standard *types* we include are not the polymorphic types, and we add polymorphic wrappers that do nothing but type erase the *concept* interface. I'd be happy with the explicit separation - for now I had no intention of adding the `standard_promise(Promise&&)` constructor, . #46 relevant here.

**Comment by dhollman** [comment]
> It's a valid conclusion as well, btw, to decide that the standard types we include are not the polymorphic types, and we add polymorphic wrappers that do nothing but type erase the concept interface.

So I tried this on a branch, and the polymorphic wrappers ended up looking almost exactly like the standard types, but with different constructors.  I'm not convinced we need both.

What's the objection to having a `standard_promise(Promise&&)` constructor? If the `OneWayExecutor` version of `make_promise_contract()` constructs the promise via internal implementation details anyway, then `standard_promise` is effectively type-erasing those internal implementation details even in the `OneWayExecutor` case.

**Comment by LeeHowes** [comment]
No objection. See my comment in #46 :) After I wrote this I looked there, rethought and have concluded much the same as you.

**Comment by dhollman** [comment]
Ah, missed the relative ordering of those two comments.  Okay, I'll write this up and put in a pull request.

**Comment by LeeHowes** [comment]
Done, and a nice consistency fix at that.
