### ISSUE TITLE
proper type erasure for `*_promise_contract_t`

### ISSUE THREAD

**Issue by dhollman** [executors/futures#97]
In order to properly type-erase the executor in the second part of the promise contract return, invocation of `then_execute` on the type-erased executor needs to be part of that type's interface (i.e., the executor and the future token or whatever need to be type-erased at the same time).  Including this in the interface for the promise contract also has the advantage that we no longer have to add the promise contract to the requirements for `ThenExecutor`

**Comment by LeeHowes** [comment]
David, is #96 and our discussion yesterday enough to satisfy you and close this issue or is there something further we need to discuss?

**Comment by dhollman** [comment]
Yes, I think so.

**Comment by LeeHowes** [comment]
Wonderful. Closing issues makes me happy.
